### ISSUE TITLE
typo in the repo-name

### ISSUE THREAD

**Issue by dlaehnemann** [snakemake-workflows/transcriptome-differential-expression#3]
I think you meant to make the repo-name:
```
transcriptome-differential-expression
```

Currently, it is missing the `c` in `transcriptome`:
```
transriptome-differential-expression 
```

I think a rename should be relatively painless, as GitHub redirects stuff, as far as I'm aware. Also, I guess this is still fairly early on in the development process.

**Comment by cmeesters** [comment]
done
