### ISSUE TITLE
add CI pipline

### ISSUE THREAD

**Issue by cmeesters** [snakemake-workflows/transcriptome-differential-expression#5]
copy CI pipeline from https://github.com/snakemake-workflows/snakemake-workflow-template/tree/main/.github/workflows

implement and test

**Comment by yeising** [comment]
Add: coda envs to rules (None for no conda).

**Comment by cmeesters** [comment]
no input given for linitin:
 needs test data, chain main.yml

**Comment by yeising** [comment]
Resolved with #90.
